### ISSUE TITLE
Cannot put NSError in syncPOST

### ISSUE THREAD

**Issue by jackyshek** [paulmelnikow/AFNetworking-Synchronous#6]
I have used the syncPOST to get the json with using swift. However, synPost need the NSErrorPointer not NSError.

Here is the Code:

var error = NSErrorPointer()
var error_mes:NSError // failed
 let josn: AnyObject! = manager.syncPOST(getCol_link, parameters: nil, operation: nil, error: error)

Error:
 Cannot invoke 'syncPOST' with an argument list of type '(String, parameters: nil, operation: nil, error: NSError)'

**Comment by paulmelnikow** [comment]
Hmmm, I'm not sure the correct fix, but don't think this is a problem with this library. Can you try posting on StackOverflow?
