### ISSUE TITLE
Hope you can update it to support AFN3.x.

### ISSUE THREAD

**Issue by Davisjy** [paulmelnikow/AFNetworking-Synchronous#7]
Hope you can update it to support AFN3.x.

**Comment by paulmelnikow** [comment]
I'm definitely open to a pull request!

**Comment by sanketsawant** [comment]
Any chances of adding AFN3.x support in near future?

**Comment by paulmelnikow** [comment]
Well… I'm definitely still open to a pull request!

**Comment by paulmelnikow** [comment]
I added support for 3.x in 7d968ec and [released in 1.1.0](https://cocoapods.org/pods/AFNetworking-Synchronous), along with docs and tests.

Let me know if you have any issues!
