### ISSUE TITLE
Support for 4.0?

### ISSUE THREAD

**Issue by StainlessStlRat** [paulmelnikow/AFNetworking-Synchronous#9]
https://github.com/AFNetworking/AFNetworking/releases

**Comment by paulmelnikow** [comment]
A pull request would be welcome!

**Comment by StainlessStlRat** [comment]
Unfortunately I already use a highly modified version. But I can tell you to the only thing I think you need if you decide to update.

You must update the GET calls with a header:(value) named parameter

**Comment by moyitpro** [comment]
I created a new pull rest with support for 4.x. I have confirmed that this is working in my app, just had to add the header parameter.
